### ISSUE TITLE
Cookies problem

### ISSUE THREAD

**Issue by Nate77Chen** [supermax1122/SE-group-NZF4#145]
After I updated the latest version from 'master' branch, the netbeans might still had cookies remained, so this error appeared when I died for a 'Hazard' and restarted in the game. This error disappeared after I reopened the netbeans.
![wechatimg269](https://cloud.githubusercontent.com/assets/22283282/26749696/8184a8ac-4864-11e7-9366-3e2a81a8f899.jpeg)

**Comment by supermax1122** [comment]
just need to clean cookie
